title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 2/4

  published:
    label: Published
    type:  text
    width: 1/4

  year:
    label: Year
    type:  text
    width: 1/4

  coverimage:
    label: Coverimage
    type:  image

  subtitle:
    label: Subtitle
    type:  text
    
  text:
    label: Text
    type:  textarea